### Create a new Session
POST    https://downunder-server.platform.alfagun74.de/session
### Create new Player
POST    https://downunder-server.platform.alfagun74.de/session/:sessionId/player
Content-Type: application/json

{
    "username":""
}
### Get game info
GET     https://downunder-server.platform.alfagun74.de/session/:sessionId/player/:playerId
### Delete a session
DELETE  https://downunder-server.platform.alfagun74.de/session/:sessionId
### Remove player from session
DELETE  https://downunder-server.platform.alfagun74.de/session/:sessionId/player/:playerId
### Draw a card
GET     https://downunder-server.platform.alfagun74.de/session/:sessionId/player/:playerId/draw
### Play a card
POST    https://downunder-server.platform.alfagun74.de/session/:sessionId/player/:playerId/play/:cardid
### Reset a session
DELETE  https://downunder-server.platform.alfagun74.de/session/rcmJV/reset
