### Create a new Session
POST    http://localhost:7777/session
### Create new Player
POST    http://localhost:7777/session/:sessionId/player
Content-Type: application/json

{
    "username":""
}
### Get game info
GET     http://localhost:7777/session/:sessionId/player/:playerId
### Delete a session
DELETE  http://localhost:7777/session/:sessionId
### Remove player from session
DELETE  http://localhost:7777/session/:sessionId/player/:playerId
### Draw a card
GET     http://localhost:7777/session/:sessionId/player/:playerId/draw
### Play a card
POST    http://localhost:7777/session/:sessionId/player/:playerId/play/:cardid
### End Turn
POST    http://localhost:7777/session/:sessionId/player/:playerId/turn
### Reset a session
DELETE  http://localhost:7777/session/:sessionId/reset